apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-nginx
  labels:
    name: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
      - fdis.ibmeet.xyz
      secretName: fdis-plan-tls
    - hosts:
      - amuzic.ibmeet.xyz
      secretName: amuzic-tls
    - hosts:
      - proxlay.ibmeet.xyz
      secretName: proxlay-tls
  rules:
  - host: fdis.ibmeet.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: fdis-plan-service
            port:
              number: 80
  - host: amuzic.ibmeet.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: amuzic-service
            port:
              number: 80
  - host: proxlay.ibmeet.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: proxlay-service
            port:
              number: 80