apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxlay-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxlay-backend-app
  template:
    metadata:
      labels:
        app: proxlay-backend-app
    spec:
      containers:
      - name: proxlay-backend-app
        image: ikrambagban/proxlay-backend:42e6333d38ec0eed9e82a150dce542f18e4661ec
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: secret
            mountPath: /app/.env
            subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: proxlay-backend-secret
            items:
              - key: .env
                path: .env